import type { Overview } from "./api";

export const localOverview: Overview = {
  generated_at: "2026-04-25",
  users: {
    student: {
      id: "stu-aarav",
      name: "Aarav Sharma",
      role: "Student",
      avatar: "AS",
      department: "Computer Science",
      email: "aarav.sharma@cmis.edu",
      bio: "Second-year undergraduate focused on data systems and applied AI.",
      skills: ["Python", "Data Structures", "SQL", "Machine Learning"],
    },
    faculty: {
      id: "fac-meena",
      name: "Dr. Meena Iyer",
      role: "Faculty",
      avatar: "MI",
      department: "Computer Science",
      email: "meena.iyer@cmis.edu",
      bio: "Associate Professor and AI pedagogy champion.",
      skills: ["Algorithms", "AI Ethics", "Assessment Design"],
    },
    admin: {
      id: "adm-rajiv",
      name: "Rajiv Menon",
      role: "Admin",
      avatar: "RM",
      department: "Academic Operations",
      email: "rajiv.menon@cmis.edu",
      bio: "Registrar driving CMIS adoption.",
      skills: ["Governance", "Analytics", "Compliance"],
    },
    it: {
      id: "it-kavya",
      name: "Kavya Nair",
      role: "IT Staff",
      avatar: "KN",
      department: "Information Technology",
      email: "kavya.nair@cmis.edu",
      bio: "Platform engineer maintaining local infrastructure.",
      skills: ["FastAPI", "Security", "Observability"],
    },
  },
  courses: [
    {
      id: "cs201",
      code: "CS201",
      title: "Data Structures & Algorithms",
      description: "Core algorithmic thinking with trees, graphs, and applied problem solving.",
      department: "Computer Science",
      term: "Monsoon 2026",
      credits: 4,
      faculty: ["Dr. Meena Iyer"],
      skills: ["Data Structures", "Algorithms", "Python"],
      prerequisites: ["CS101"],
      status: "Published",
      capacity: 64,
      enrolled: 58,
      waitlist: 4,
      adoption: 87,
      average_grade: 8.4,
    },
    {
      id: "ai310",
      code: "AI310",
      title: "Responsible AI Systems",
      description: "Ethical, explainable, and human-centered AI systems.",
      department: "Computer Science",
      term: "Monsoon 2026",
      credits: 3,
      faculty: ["Dr. Meena Iyer"],
      skills: ["AI Ethics", "ML Evaluation", "Policy"],
      prerequisites: ["CS201"],
      status: "Published",
      capacity: 48,
      enrolled: 46,
      waitlist: 2,
      adoption: 91,
      average_grade: 8.7,
    },
  ],
  enrollments: [
    { id: "enr-001", student_id: "stu-aarav", course_id: "cs201", status: "Active", progress: 72, deadline_risk: "Low" },
    { id: "enr-002", student_id: "stu-aarav", course_id: "ai310", status: "Active", progress: 54, deadline_risk: "Medium" },
  ],
  submissions: [
    {
      id: "sub-301",
      assessment_id: "asm-101",
      student_id: "stu-aarav",
      student_name: "Aarav Sharma",
      course_id: "cs201",
      status: "Submitted",
      submitted_at: "2026-04-23T21:18:00",
      text: "Implemented Dijkstra and A* variants with runtime analysis.",
      similarity_score: 0.11,
      score: null,
      feedback: "",
    },
  ],
  gradebook: [
    { course: "Data Structures & Algorithms", assessment: "Heap Quiz", score: 22, max_score: 25, weight: 10, trend: "up" },
    { course: "Responsible AI Systems", assessment: "Governance Memo", score: null, max_score: 50, weight: 25, trend: "pending" },
  ],
  heatmap: [
    { department: "Computer Science", role: "Student", login_frequency: 94, feature_depth: 88, forum_participation: 76, score: 86.6, band: "High", sentiment: 0.72, negative_clusters: ["Students want more sample answers"] },
    { department: "Management", role: "Faculty", login_frequency: 67, feature_depth: 61, forum_participation: 48, score: 58.9, band: "Low", sentiment: 0.41, negative_clusters: ["Teachers want clearer dashboard wording"] },
    { department: "Civil Engineering", role: "Faculty", login_frequency: 42, feature_depth: 36, forum_participation: 27, score: 35.1, band: "Critical", sentiment: 0.22, negative_clusters: ["Teachers need help moving assignments online"] },
  ],
  process_debt: [
    { workflow: "Course Approval", score: 15.2, percentile: 88, status: "Red", trend: [{ month: "Jan", score: 18.4 }, { month: "Apr", score: 15.2 }], recommendations: ["Remove one repeated review step"] },
    { workflow: "Posting Grades", score: 7.9, percentile: 54, status: "Amber", trend: [{ month: "Jan", score: 9.1 }, { month: "Apr", score: 7.9 }], recommendations: ["Notify reviewers at the same time"] },
  ],
  decision_map: {
    nodes: [
      { id: "faculty", label: "Teacher", role: "Starts request", risk: "normal", x: 80, y: 140 },
      { id: "hod", label: "Dept. Head", role: "Reviews", risk: "bottleneck", x: 250, y: 80 },
      { id: "registrar", label: "Registrar", role: "Approver", risk: "normal", x: 650, y: 80 },
      { id: "prof-x", label: "Extra Step", role: "Unexpected", risk: "anomaly", x: 470, y: 250 },
    ],
    edges: [
      { source: "faculty", target: "hod", type: "intended", volume: 38 },
      { source: "hod", target: "registrar", type: "intended", volume: 30 },
      { source: "faculty", target: "prof-x", type: "deviation", volume: 3 },
      { source: "prof-x", target: "registrar", type: "deviation", volume: 3 },
    ],
    anomalies: ["One teacher approved 3 syllabus updates before department review."],
  },
  knowledge_continuity: [
    { course: "Compiler Design", department: "Computer Science", sole_instructor_terms: 5, faculty: "Dr. Ishan Gupta", retirement_window: "18 months", risk_score: 92, severity: "Critical", suggestions: ["Assign co-instructor", "Record lecture archive"] },
  ],
  pathways: {
    "stu-aarav": {
      student_id: "stu-aarav",
      mastery_probability: 0.68,
      predicted_outcome: "On Track with Watch",
      estimated_time: "4h 30m",
      skills: [
        { name: "Graph Traversal", mastery: 82 },
        { name: "Dynamic Programming", mastery: 58 },
      ],
      next_steps: [
        { title: "Dynamic Programming Practice Round", course: "CS201", type: "Practice Set", estimated_time: "75 min", reason: "Recent quiz work shows this topic needs one more practice round.", priority: "High" },
      ],
    },
  },
  chat_history: { cs201: [{ role: "assistant", content: "Welcome back, Aarav.", provider: "local" }] },
  certificates: [
    { id: "cert-001", student_id: "stu-aarav", course: "Python Foundations", grade: "A", issued_at: "2026-02-12", hash: "0x9f33b7c088fa2dc0f41f88c78e8d64221d81f309e84c2f6bcf9b8cdbb0e9b217", chain: "Polygon Mumbai", tx_hash: "0x8b9f0d2c7a71f14a98b7d50cc0a4021021f78d3726", status: "Verified", badges: ["Completed Data Structures Unit 4"] },
  ],
  gamification: {
    student_id: "stu-aarav",
    xp: 1840,
    level: 7,
    next_level_xp: 2200,
    rank: 4,
    opt_in_leaderboard: true,
    wallet_events: [{ label: "Answered peer question", xp: 15, date: "2026-04-24" }],
    badges: ["First Post", "Top Helper", "30-Day Streak"],
    redeemable_perks: ["Priority lab slot"],
    leaderboard: [{ name: "Aarav Sharma", xp: 1840 }],
  },
  alumni_skill_gaps: [
    { skill: "MLOps", demand_score: 91, curriculum_coverage: 42, gap_score: 49, affected_courses: ["Responsible AI Systems"], suggestion: "Add deployment and monitoring lab.", faculty_response: "Draft syllabus update requested" },
  ],
  change_management: {
    framework: "Lewin + Kotter",
    rollout: [{ stage: "Change", status: "Active", details: "Champion network and role-based training sessions." }],
    champions: [{ name: "Dr. Meena Iyer", department: "Computer Science", impact: "91% faculty analytics adoption" }],
    training_sessions: [{ title: "Faculty Analytics Studio", date: "2026-04-28", attendance: 36, status: "Scheduled" }],
  },
  audit_log: [
    { timestamp: "2026-04-25T09:42:00", actor: "Rajiv Menon", role: "Admin", action: "Viewed process debt dashboard", risk: "Low" },
  ],
  kpis: [
    { label: "Students Staying", value: "91.4%", delta: "+5.2 pp", tone: "green" },
    { label: "Average Grade", value: "8.12", delta: "+0.34", tone: "blue" },
    { label: "Workflow Load", value: "8.6", delta: "-30%", tone: "amber" },
  ],
  free_tier_stack: [
    { service: "Backend", provider: "FastAPI + Uvicorn", status: "Local", limit: "No cloud cost" },
    { service: "LLM", provider: "Groq Chat Completions", status: "Configured by GROQ_API_KEY", limit: "Local guidance when unavailable" },
  ],
  api_endpoints: [
    "GET /health",
    "GET /api/v1/overview",
    "GET /api/v1/search",
    "GET /api/v1/users/me",
    "GET /api/v1/courses",
    "POST /api/v1/enrollments",
    "GET /api/v1/student/{student_id}/study-plan",
    "GET /api/v1/student/{student_id}/course-registration",
    "GET /api/v1/student/{student_id}/certificates",
    "POST /api/v1/chat/{course_id}/message",
    "POST /api/v1/grading/suggest",
    "PATCH /api/v1/submissions/{submission_id}/grade",
    "POST /api/v1/certificates/verify/{hash}",
    "GET /api/v1/faculty/{faculty_id}/classes",
    "GET /api/v1/faculty/{faculty_id}/grading-queue",
    "GET /api/v1/faculty/course-improvements",
    "GET /api/v1/admin/campus-kpis",
    "GET /api/v1/admin/departments-needing-help",
    "GET /api/v1/admin/workflow-delays",
    "POST /api/v1/admin/workflow-actions",
    "GET /api/v1/admin/approval-route",
    "GET /api/v1/it/system-health",
    "GET /api/v1/it/dependency-map",
    "GET /api/v1/it/capacity-monitor",
    "GET /api/v1/it/api-surface",
    "GET /api/v1/it/privacy-controls",
    "GET /api/v1/it/audit-trail",
  ],
  system: { groq_configured: false, groq_model: "llama-3.1-8b-instant", local_mode: true },
};
